<?php

namespace Database\Seeders;

use App\Models\Spec;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SpecSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $specs = [
            [ 'kategori'=>'tipe_barang','tipe'=>'Perhiasan','kode_tipe'=>7,'nomor_tipe'=>7,'nama'=> null, 'codename'=> 7, 'name_id'=>7 ],
            [ 'kategori'=>'tipe_barang','tipe'=>'LM','kode_tipe'=>8,'nomor_tipe'=>8,'nama'=> null, 'codename'=> 8, 'name_id'=>8 ],
            [ 'kategori'=>'tipe_perhiasan','tipe'=>'Anting','kode_tipe'=>'AT','nomor_tipe'=>1,'nama'=> 'Desy', 'codename'=> 'Des', 'name_id'=> 1 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Anting','kode_tipe'=>'AT','nomor_tipe'=>1,'nama'=> 'Desy Polos', 'codename'=> 'DesP', 'name_id'=> 2 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Anting','kode_tipe'=>'AT','nomor_tipe'=>1,'nama'=> 'Gipsy', 'codename'=> 'Gip', 'name_id'=> 3 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Anting','kode_tipe'=>'AT','nomor_tipe'=>1,'nama'=> 'Jepit', 'codename'=> 'Jp', 'name_id'=> 5 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Anting','kode_tipe'=>'AT','nomor_tipe'=>1,'nama'=> 'Jepit Polos', 'codename'=> 'JpP', 'name_id'=> 6 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Anting','kode_tipe'=>'AT','nomor_tipe'=>1,'nama'=> 'Kait', 'codename'=> 'K', 'name_id'=> 1 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Anting','kode_tipe'=>'AT','nomor_tipe'=>1,'nama'=> 'Kait Panjang', 'codename'=> 'KPj', 'name_id'=> 7 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Anting','kode_tipe'=>'AT','nomor_tipe'=>1,'nama'=> 'Kenip', 'codename'=> 'Ken', 'name_id'=> 8 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Anting','kode_tipe'=>'AT','nomor_tipe'=>1,'nama'=> 'Tusuk Sate', 'codename'=> 'Tussat', 'name_id'=> 9 ],
            [ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Mata Burung', 'codename'=>'MBur', 'name_id'=> 1 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Mata Desy', 'codename'=>'MDes', 'name_id'=> 2 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Pentol Polos', 'codename'=>'PenPol', 'name_id'=> 3 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Kembang Polos', 'codename'=>'KemPol', 'name_id'=> 5 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Kembang Mata', 'codename'=>'Kemat', 'name_id'=> 6 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Hello Kitty', 'codename'=>'HKit', 'name_id'=> 7 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Tribal', 'codename'=>'Tri', 'name_id'=> 8 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'1/2 Tribal', 'codename'=>'1/2Tri', 'name_id'=> 9 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Bintang', 'codename'=>'Bin', 'name_id'=> 10 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Chanel', 'codename'=>'Ch', 'name_id'=> 11 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Love', 'codename'=>'Lov', 'name_id'=> 12 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Segitiga', 'codename'=>'Segi3', 'name_id'=> 15 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Kotak', 'codename'=>'Kotak', 'name_id'=> 16 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Fashion', 'codename'=>'Fash', 'name_id'=> 17 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Tribal Pasir', 'codename'=>'TriPas', 'name_id'=> 18 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Tribal Ukir', 'codename'=>'TriKir', 'name_id'=> 19 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Giwang','kode_tipe'=>'GW','nomor_tipe'=>2,'nama'=>'Panjang', 'codename'=>'Pjg', 'name_id'=> 20 ],
            [ 'kategori'=>'tipe_perhiasan','tipe'=>'Cincin','kode_tipe'=>'CC','nomor_tipe'=>3,'nama'=> '1/2 Rantai', 'codename'=> '1/2R', 'name_id'=> 1 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Cincin','kode_tipe'=>'CC','nomor_tipe'=>3,'nama'=> '1/2 Pasir', 'codename'=> '1/2P', 'name_id'=> 2 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Cincin','kode_tipe'=>'CC','nomor_tipe'=>3,'nama'=> 'Bambu Ukir', 'codename'=> 'Bambuk', 'name_id'=> 3 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Cincin','kode_tipe'=>'CC','nomor_tipe'=>3,'nama'=> 'Dubai', 'codename'=> 'Dub.', 'name_id'=> 5 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Cincin','kode_tipe'=>'CC','nomor_tipe'=>3,'nama'=> 'Listring Aurel', 'codename'=> 'listr.Aurel', 'name_id'=> 6 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Cincin','kode_tipe'=>'CC','nomor_tipe'=>3,'nama'=> 'Listring V', 'codename'=> 'listr.V', 'name_id'=> 7 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Cincin','kode_tipe'=>'CC','nomor_tipe'=>3,'nama'=> 'Patkok', 'codename'=> 'Patk', 'name_id'=> 8 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Cincin','kode_tipe'=>'CC','nomor_tipe'=>3,'nama'=> 'Ring Polos', 'codename'=> 'r.Pol', 'name_id'=> 9 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Cincin','kode_tipe'=>'CC','nomor_tipe'=>3,'nama'=> 'Stempel', 'codename'=> 'Stp.', 'name_id'=> 10 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Cincin','kode_tipe'=>'CC','nomor_tipe'=>3,'nama'=> 'Wedding/Kawin', 'codename'=> 'Wed', 'name_id'=> 11 ],
            // Kalung
            [ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Biji Lada', 'codename'=> 'BiLa', 'name_id'=> 1 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Nori', 'codename'=> 'Nor', 'name_id'=> 2 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Balok Mini', 'codename'=> 'BalMin', 'name_id'=> 3 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Nori Balok', 'codename'=> 'NoLok', 'name_id'=> 5 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Nori Balok Ukir', 'codename'=> 'NoLokIr', 'name_id'=> 6 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Sela-Seli/Lovina', 'codename'=> 'SelSelov', 'name_id'=> 7 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Plexi', 'codename'=> 'Plex', 'name_id'=> 8 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Santa', 'codename'=> 'San', 'name_id'=> 9 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Cassandra', 'codename'=> 'Cas', 'name_id'=> 10 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Cassandra Ukir', 'codename'=> 'CasUk', 'name_id'=> 11 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Boston', 'codename'=> 'Bos', 'name_id'=> 12 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Sisik Naga', 'codename'=> 'SiNa', 'name_id'=> 15 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Gepeng', 'codename'=> 'Gep', 'name_id'=> 16 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Milano Bulat', 'codename'=> 'Milat', 'name_id'=> 17 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Milano Kotak', 'codename'=> 'Mitak', 'name_id'=> 18 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Milano Gepeng', 'codename'=> 'Mipeng', 'name_id'=> 19 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Tambang Lilit', 'codename'=> 'Talit', 'name_id'=> 20 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Tambang Variasi', 'codename'=> 'Tasi', 'name_id'=> 21 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Rantai Gepeng', 'codename'=> 'Rapeng', 'name_id'=> 22 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Biji Cabe', 'codename'=> 'BiCa', 'name_id'=> 23 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Biji Timun', 'codename'=> 'BiMun', 'name_id'=> 25 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Biji Timun Lilit', 'codename'=> 'BiTiLit', 'name_id'=> 26 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Biji Padi', 'codename'=> 'BiDi', 'name_id'=> 27 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Holo', 'codename'=> 'Hol', 'name_id'=> 28 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Holo Safir', 'codename'=> 'HolSaf', 'name_id'=> 29 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Holo Ukir', 'codename'=> 'Holuk', 'name_id'=> 30 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Silinder', 'codename'=> 'Sil', 'name_id'=> 31 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Italy', 'codename'=> 'It', 'name_id'=> 32 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Italy Kaca', 'codename'=> 'ItCa', 'name_id'=> 33 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Italy Santa', 'codename'=> 'ItSan', 'name_id'=> 35 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Aurel', 'codename'=> 'Aurel', 'name_id'=> 36 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Kalung','kode_tipe'=>'KL','nomor_tipe'=>5,'nama'=> 'Miyata', 'codename'=> 'Miya', 'name_id'=> 37 ],
            [ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Rantai','kode_tipe'=>'GLR','nomor_tipe'=>6,'nama'=> 'Rantai Gepeng', 'codename'=>'Rapeng', 'name_id'=> 1 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Rantai','kode_tipe'=>'GLR','nomor_tipe'=>6,'nama'=> 'Holo', 'codename'=>'Hol', 'name_id'=> 2 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Rantai','kode_tipe'=>'GLR','nomor_tipe'=>6,'nama'=> 'Holo Ukir', 'codename'=>'Holuk', 'name_id'=> 3 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Rantai','kode_tipe'=>'GLR','nomor_tipe'=>6,'nama'=> 'Holo Safir', 'codename'=>'HolSaf', 'name_id'=> 5 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Rantai','kode_tipe'=>'GLR','nomor_tipe'=>6,'nama'=> 'Holo Kombinasi', 'codename'=>'HolKomb', 'name_id'=> 6 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Rantai','kode_tipe'=>'GLR','nomor_tipe'=>6,'nama'=> 'Sisik Naga', 'codename'=>'SiNa', 'name_id'=> 7 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Rantai','kode_tipe'=>'GLR','nomor_tipe'=>6,'nama'=> 'Sisik Naga Double', 'codename'=>'SiNaDou', 'name_id'=> 8 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Rantai','kode_tipe'=>'GLR','nomor_tipe'=>6,'nama'=> 'Susun Sirih', 'codename'=>'SusSir', 'name_id'=> 9 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Rantai','kode_tipe'=>'GLR','nomor_tipe'=>6,'nama'=> 'Cor', 'codename'=>'Cor', 'name_id'=> 10 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Rantai','kode_tipe'=>'GLR','nomor_tipe'=>6,'nama'=> 'Serut', 'codename'=>'Serut', 'name_id'=> 11 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Rantai','kode_tipe'=>'GLR','nomor_tipe'=>6,'nama'=> 'Biji Lada Kombinasi', 'codename'=>'BiLaKomb', 'name_id'=> 12 ],
			// Gelang Bulet
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Bulat','kode_tipe'=>'GLB','nomor_tipe'=>7,'nama'=> 'Cartier', 'codename'=>'Car', 'name_id'=> 1 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Bulat','kode_tipe'=>'GLB','nomor_tipe'=>7,'nama'=> 'Gelombang', 'codename'=>'Gelo', 'name_id'=> 2 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Bulat','kode_tipe'=>'GLB','nomor_tipe'=>7,'nama'=> 'Keroncong', 'codename'=>'Keron', 'name_id'=> 3 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Bulat','kode_tipe'=>'GLB','nomor_tipe'=>7,'nama'=> 'Fashion', 'codename'=>'Fash', 'name_id'=> 5 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Gelang Bulat','kode_tipe'=>'GLB','nomor_tipe'=>7,'nama'=> 'Ular', 'codename'=>'Ular', 'name_id'=> 6 ],
            // Liontin
            [ 'kategori'=>'tipe_perhiasan','tipe'=>'Liontin','kode_tipe'=>'Lion','nomor_tipe'=>8,'nama'=> 'Desy', 'codename'=> 'Des', 'name_id'=> 1 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Liontin','kode_tipe'=>'Lion','nomor_tipe'=>8,'nama'=> 'Chanel', 'codename'=> 'Ch', 'name_id'=> 2 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Liontin','kode_tipe'=>'Lion','nomor_tipe'=>8,'nama'=> 'Louis Vuitton', 'codename'=> 'LV', 'name_id'=> 3 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Liontin','kode_tipe'=>'Lion','nomor_tipe'=>8,'nama'=> 'Gucci', 'codename'=> 'Guc', 'name_id'=> 5 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Liontin','kode_tipe'=>'Lion','nomor_tipe'=>8,'nama'=> 'Salib', 'codename'=> 'Salib', 'name_id'=> 6 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Liontin','kode_tipe'=>'Lion','nomor_tipe'=>8,'nama'=> 'Batu', 'codename'=> 'Batu', 'name_id'=> 7 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Liontin','kode_tipe'=>'Lion','nomor_tipe'=>8,'nama'=> 'Anggur', 'codename'=> 'Anggur', 'name_id'=> 8 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Liontin','kode_tipe'=>'Lion','nomor_tipe'=>8,'nama'=> 'Huruf', 'codename'=> 'Hur', 'name_id'=> 9 ],
			[ 'kategori'=>'tipe_perhiasan','tipe'=>'Liontin','kode_tipe'=>'Lion','nomor_tipe'=>8,'nama'=> 'Dubai Ukir Pohon Kelapa', 'codename'=> 'DubUkPoKel', 'name_id'=> 10 ],
            [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'biru1', 'name_id'=> 1, 'codename'=> 'mb' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'biru5', 'name_id'=> 2, 'codename'=> 'mb5' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'biru9', 'name_id'=> 3, 'codename'=> 'mb9' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'coklat1', 'name_id'=> 5, 'codename'=> 'mc' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'coklat5', 'name_id'=> 6, 'codename'=> 'mc5' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'coklat9', 'name_id'=> 7, 'codename'=> 'mc9' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'hijau1', 'name_id'=> 8, 'codename'=> 'mhj' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'hijau5', 'name_id'=> 9, 'codename'=> 'mhj5' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'hijau9', 'name_id'=> 10, 'codename'=> 'mhj9' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'hitam1', 'name_id'=> 11, 'codename'=> 'mht' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'hitam5', 'name_id'=> 12, 'codename'=> 'mht5' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'hitam9', 'name_id'=> 15, 'codename'=> 'mht9' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'kuning1', 'name_id'=> 16, 'codename'=> 'mk' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'kuning5', 'name_id'=> 17, 'codename'=> 'mk5' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'kuning9', 'name_id'=> 18, 'codename'=> 'mk9' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'merah1', 'name_id'=> 19, 'codename'=> 'mm' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'merah5', 'name_id'=> 20, 'codename'=> 'mm5' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'merah9', 'name_id'=> 21, 'codename'=> 'mm9' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'orange1', 'name_id'=> 22, 'codename'=> 'mor' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'orange5', 'name_id'=> 23, 'codename'=> 'mor5' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'orange9', 'name_id'=> 25, 'codename'=> 'mor9' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'pink1', 'name_id'=> 26, 'codename'=> 'mpink' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'pink5', 'name_id'=> 27, 'codename'=> 'mpink5' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'pink9', 'name_id'=> 28, 'codename'=> 'mpink9' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'ungu1', 'name_id'=> 29, 'codename'=> 'mu' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'ungu5', 'name_id'=> 30, 'codename'=> 'mu5' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'ungu9', 'name_id'=> 31, 'codename'=> 'mu9' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'putih', 'name_id'=> 32, 'codename'=> 'mp' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'putih kabut', 'name_id'=> 33, 'codename'=> 'mp5' ],
	        [ 'kategori'=>'mata','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'putih susu', 'name_id'=> 35, 'codename'=> 'mp9' ],
            [ 'kategori'=>'mainan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'Bola', 'name_id'=> 1, 'codename'=> 'maiBola' ],
            [ 'kategori'=>'mainan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'Dora', 'name_id'=> 2, 'codename'=> 'maiDora' ],
            [ 'kategori'=>'mainan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'Hello Kitty', 'name_id'=> 3, 'codename'=> 'maiHelloKitty' ],
            [ 'kategori'=>'mainan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'Lonceng', 'name_id'=> 5, 'codename'=> 'maiLonceng' ],
            [ 'kategori'=>'mainan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'Patrick', 'name_id'=> 6, 'codename'=> 'maiPatrick' ],
            [ 'kategori'=>'mainan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'SpongeBob', 'name_id'=> 7, 'codename'=> 'maiSpongeBob' ],
            [ 'kategori'=>'ukuran','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'Z', 'name_id'=>0 ],
            [ 'kategori'=>'ukuran','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'J', 'name_id'=>1 ],
            [ 'kategori'=>'ukuran','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N', 'name_id'=>2 ],
            [ 'kategori'=>'ukuran','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'S', 'name_id'=>3 ],
            [ 'kategori'=>'ukuran','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'E', 'name_id'=>4 ],
            [ 'kategori'=>'ukuran','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'Q', 'name_id'=>5 ],
            [ 'kategori'=>'ukuran','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'L', 'name_id'=>6 ],
            [ 'kategori'=>'ukuran','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'C', 'name_id'=>7 ],
            [ 'kategori'=>'ukuran','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'P', 'name_id'=>8 ],
            [ 'kategori'=>'ukuran','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'i', 'name_id'=>9 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'NONE', 'name_id'=> 0 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N1', 'name_id'=> 1 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N2', 'name_id'=> 2 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N3', 'name_id'=> 3 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N4', 'name_id'=> 4 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N5', 'name_id'=> 5 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N6', 'name_id'=> 6 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N7', 'name_id'=> 7 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N8', 'name_id'=> 8 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N9', 'name_id'=> 9 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N10', 'name_id'=> 10 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N11', 'name_id'=> 11 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N12', 'name_id'=> 12 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N13', 'name_id'=> 13 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N14', 'name_id'=> 14 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N15', 'name_id'=> 15 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N16', 'name_id'=> 16 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N17', 'name_id'=> 17 ],
            [ 'kategori'=>'nampan','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>null,'codename'=>'N18', 'name_id'=> 18 ],
            [ 'kategori'=>'range_usia','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'dewasa', 'name_id'=> 1, 'codename'=> 'ru.dewasa' ],
            [ 'kategori'=>'range_usia','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'anak', 'name_id'=> 2, 'codename'=> 'ru.anak' ],
            [ 'kategori'=>'range_usia','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'bayi', 'name_id'=> 3, 'codename'=> 'ru.bayi' ],
            [ 'kategori'=>'warna_emas','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'kuning', 'name_id'=> 1, 'codename'=> 'we.kuning' ],
            [ 'kategori'=>'warna_emas','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'putih', 'name_id'=> 2, 'codename'=> 'we.putih' ],
            [ 'kategori'=>'warna_emas','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'poles', 'name_id'=> 3, 'codename'=> 'we.poles' ],
            [ 'kategori'=>'warna_emas','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'chrome', 'name_id'=> 5, 'codename'=> 'we.chrome' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'3', 'name_id'=> 1, 'codename'=> 'c.3' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'300', 'name_id'=> 2, 'codename'=> 'c.300' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'375', 'name_id'=> 3, 'codename'=> 'c.375' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'8K', 'name_id'=> 5, 'codename'=> 'c.8K' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'A', 'name_id'=> 6, 'codename'=> 'c.A' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'A33', 'name_id'=> 7, 'codename'=> 'c.A33' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'AYU', 'name_id'=> 8, 'codename'=> 'c.AYU' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'B', 'name_id'=> 9, 'codename'=> 'c.B' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'HT300', 'name_id'=> 10, 'codename'=> 'c.HT300' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'J', 'name_id'=> 11, 'codename'=> 'c.J' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'KY', 'name_id'=> 12, 'codename'=> 'c.KY' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'N', 'name_id'=> 15, 'codename'=> 'c.N' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'NX', 'name_id'=> 16, 'codename'=> 'c.NX' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'O', 'name_id'=> 17, 'codename'=> 'c.O' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'STM', 'name_id'=> 18, 'codename'=> 'c.STM' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'gCheck', 'name_id'=> 19, 'codename'=> 'c.gCheck' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'gBintang2', 'name_id'=> 20, 'codename'=> 'c.gBin2' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'gBintangBulan', 'name_id'=> 21, 'codename'=> 'c.gBinBul' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'gRoaster', 'name_id'=> 22, 'codename'=> 'c.gRoaster' ],
            [ 'kategori'=>'cap','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=>'gSBintang', 'name_id'=> 23, 'codename'=> 'c.gSBin' ],
            [ 'kategori'=>'kondisi','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'MULUS', 'name_id'=> 99, 'codename'=> 'MULUS' ],
            [ 'kategori'=>'kondisi','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '9', 'name_id'=> 9, 'codename'=> 'k.9' ],
            [ 'kategori'=>'kondisi','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '8', 'name_id'=> 8, 'codename'=> 'k.8' ],
            [ 'kategori'=>'kondisi','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '7', 'name_id'=> 7, 'codename'=> 'k.7' ],
            [ 'kategori'=>'kondisi','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '6', 'name_id'=> 6, 'codename'=> 'k.6' ],
            [ 'kategori'=>'kondisi','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '5', 'name_id'=> 5, 'codename'=> 'k.5' ],
            [ 'kategori'=>'kadar','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '30', 'name_id'=> 1, 'codename'=>'30' ],
            [ 'kategori'=>'kadar','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '35', 'name_id'=> 2, 'codename'=>'35' ],
            [ 'kategori'=>'kadar','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '37.5', 'name_id'=> 3, 'codename'=>'37.5' ],
            [ 'kategori'=>'kadar','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '40', 'name_id'=> 5, 'codename'=>'40' ],
            [ 'kategori'=>'kadar','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '42', 'name_id'=> 6, 'codename'=>'42' ],
            [ 'kategori'=>'kadar','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '45', 'name_id'=> 7, 'codename'=>'45' ],
            [ 'kategori'=>'kadar','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '48', 'name_id'=> 8, 'codename'=>'48' ],
            [ 'kategori'=>'kadar','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '50', 'name_id'=> 9, 'codename'=>'50' ],
            [ 'kategori'=>'kadar','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '70', 'name_id'=> 10, 'codename'=>'70' ],
            [ 'kategori'=>'kadar','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '75', 'name_id'=> 11, 'codename'=>'75' ],
            [ 'kategori'=>'kadar','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> '95', 'name_id'=> 12, 'codename'=>'95' ],
            [ 'kategori'=>'merek','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'UBS', 'name_id'=> 1, 'codename'=>'merk.UBS' ],
            [ 'kategori'=>'merek','tipe'=>null,'kode_tipe'=>null,'nomor_tipe'=>null,'nama'=> 'Antam', 'name_id'=> 2, 'codename'=>'merk.Antam' ],
        ];
        for ($i = 0; $i < count($specs); $i++) {
            Spec::create([
                'kategori' => $specs[$i]['kategori'],
                'tipe' => $specs[$i]['tipe'],
                'kode_tipe' => $specs[$i]['kode_tipe'],
                'nomor_tipe' => $specs[$i]['nomor_tipe'],
                'nama' => $specs[$i]['nama'],
                'name_id' => $specs[$i]['name_id'],
                'codename' => $specs[$i]['codename'],
            ]);
        }
    }
}
